### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by sooheon** [calrobertlee/roam-css-styles#1]
I realize actual mobile support is a lot of work, but is it possible to do something like "revert to default css at mobile size breakpoint"? 

I ask because currently the vertical right hand menu and the central floating search bar are not ideal for mobile.

**Comment by calrobertlee** [comment]
Hi sooheon,

Thanks for bringing this to my attention.  I added a breakpoint at 750px.

Replace your _entire_ css file with this single line of code:

`@import url('https://calrobertlee.github.io/roam-themes/core.css') only screen and (min-width: 750px);`

I will be making further updates to the core.css theme, so things are subject to change in a week or so, thanks for understanding!

**Comment by sooheon** [comment]
Good stuff, I like the change to an import as it takes care of updates, and avoids the ridiculously slow page load for large code blocks in roam. 

Is there a link for the light version? I actually use that one :)

**Comment by calrobertlee** [comment]
Agreed, it's much better this way

Here's the light version:
`@import url('https://calrobertlee.github.io/roam-themes/aquae.css') only screen and (min-width: 750px);`

Enjoy the theme :)

**Comment by sooheon** [comment]
Thanks!
