### ISSUE TITLE
Block embeds are not set to dark

### ISSUE THREAD

**Issue by welfvh** [calrobertlee/roam-css-styles#12]

**Comment by welfvh** [comment]
Edit: Block in Block embeds*

**Comment by calrobertlee** [comment]
Hi welfvh, which theme is this for?  Also, could you paste the block embed string for me please?  Thanks! I'll update it asap

**Comment by charlesg** [comment]
I found I have this problem with **Nox**. I have Nox though I currently have 2.1.4 which means I should update.

But blocks with `{{[[embed]]: ((someblockID))}}` which embeds the whole block in a new location shows the blocks but the theme is missing.

**Comment by calrobertlee** [comment]
Hi charlesg, thanks for reaching out, I always appreciate any issues that are brought to my attention

Could you try updating your Nox theme by using this line below as your theme?

`@import url('https://calrobertlee.github.io/roam-themes/nox.css');`

This theme will automatically update from this point forward so you'll always be up to date!

Please let me know if the issue still persists after you update.
