### ISSUE TITLE
Pomodoro blocks are unreadable

### ISSUE THREAD

**Issue by abugosh** [calrobertlee/roam-css-styles#13]
When using the pomodoro feature `{{[[POMO]]: 25}}` the rendered blocks have a transparent background (under `.rm-pomodoro`) and the default font coloring making the blocks appear as an outline with a tomato when using the dark themes.

Ideally the theme would set a reasonable background color for the button.

**Comment by calrobertlee** [comment]
Hi abugosh, I styled the Nox pomo and it is live now!

Thanks for bringing this to my attention, I appreciate your writing out the roam command and the css class as well

**Comment by abugosh** [comment]
Looks great! Thank you so much for the update!
