### ISSUE TITLE
Search disappeared

### ISSUE THREAD

**Issue by diverbroski** [calrobertlee/roam-css-styles#15]
As of yesterday, the search has disappeared from the UX. When I disable the CSS, it pops back up. Perhaps this was caused by the recent Roam update?

**Comment by calrobertlee** [comment]
Thanks for bringing this up to my attention, I'll get to this today and update you

**Comment by charlesg** [comment]
Same here. The search box is back to white but the text in it is still light gray so I had to disable Nox for the time being.

**Comment by calrobertlee** [comment]
Thanks @charlesg and @diverbroski, it should be fixed now!
