### ISSUE TITLE
Help (at bottom right) disappear?

### ISSUE THREAD

**Issue by hanct** [calrobertlee/roam-css-styles#17]
Hi,

There is a help icon at the bottom right corner, but after applying the theme NOX, it seems to disappear?

**Comment by calrobertlee** [comment]
Hi hanct! that is design by purpose

To reveal it you need to add another line under the import line, it should look like this:
`@import url('https://calrobertlee.github.io/roam-themes/nox.css');`
`#buffer {`
`    visibility: visible;`
`}`
