### ISSUE TITLE
Darktheme Highlight

### ISSUE THREAD

**Issue by b1uegh0st** [calrobertlee/roam-css-styles#19]
Hi, I tried both Nox and Lux, somehow the hightlighted text looks like this. I also try changing the css under here to something else but there is no effect. 

Was there a change in how Roam use the CSS file?

`--highlight-font-color: var(--theme-gray-1);
    --highlight-background-color: #213784;
    --highlight-link-color: var(--theme-blue-1);
    --highlight-padding: 4px 5px 4px 5px;`

![image](https://user-images.githubusercontent.com/6695697/103081569-c72a7d80-460a-11eb-8583-440926b3fc25.png)

**Comment by calrobertlee** [comment]
Hi b1uegh0st, thanks for checking in about this

Could you possibly try something out for me first to see if it fixes the isse?

Please replace all of the Nox css code on your end with this single import line:

`@import url('https://calrobertlee.github.io/roam-themes/nox.css');`

Let me know if that solves the issue!

**Comment by b1uegh0st** [comment]
Somehow my Roam instant read the link as this (suspecting something weird with the URL, trying to figure out, will keep you posted as I try).
![image](https://user-images.githubusercontent.com/6695697/103087995-eed61180-461b-11eb-9d5d-9554086fec8f.png)


Currently I am just copy-pasting raw CSS from your repo.

**Comment by b1uegh0st** [comment]
Update:
Got it to work _inside_ a CSS code block. Sorry I didn't know one have to do it. 
![image](https://user-images.githubusercontent.com/6695697/103088585-d666f680-461d-11eb-833c-52aa41917d13.png)

Result of highlighting (still) 
![image](https://user-images.githubusercontent.com/6695697/103088601-e2eb4f00-461d-11eb-909d-aae22b3b2bfd.png)

**Comment by b1uegh0st** [comment]
Confirmed fix. Thanks a bunch.

![image](https://user-images.githubusercontent.com/6695697/103140153-d6e2b880-4715-11eb-8611-cb3657d4dfa9.png)

**Comment by b1uegh0st** [comment]
Somehow the problem comeback. Changed: Did install Roam42, not sure if that affects.

![image](https://user-images.githubusercontent.com/6695697/103196454-d107f580-4916-11eb-8c02-d2941cc48b48.png)

**Comment by b1uegh0st** [comment]
Hi,

Do some inspection, it seems to be **.rm-highlight** instead of **.roam-highlight**
![image](https://user-images.githubusercontent.com/6695697/103256870-5d6ef280-49c1-11eb-82c0-8fe44aeeeecb.png)

I changed that in core.css (copied from your repo) and use Nox with it. It works now.

**Comment by b1uegh0st** [comment]
Can be closed now
