### ISSUE TITLE
Left-menu z-index on mobile Safari

### ISSUE THREAD

**Issue by msutherl** [calrobertlee/roam-css-styles#20]
When expanding the left menu in Safari mobile, the menu renders behind the text of the current page and becomes un-clickable

**Comment by msutherl** [comment]
Temporarily fixed with

```
.roam-sidebar-container {
  z-index: 999 !important;
}
```

**Comment by calrobertlee** [comment]
Thanks for bringing this to my attention Morgan! Much appreciated, hope you are having a great start to 2021
