### ISSUE TITLE
Unreadable blocks when embeded blocks are embeded again

### ISSUE THREAD

**Issue by glatteispogo** [calrobertlee/roam-css-styles#23]
When I embed a block which has itself another block embedded, the last one has  very light background. so I cant read it anymore.

(This may be the same suggestion as "Block quote" here, but I think its not only a request, but a real problem: https://github.com/calrobertlee/roam-css-styles/pull/18

(not familiar with github, i hope, I did it right, writing it here)

![grafik](https://user-images.githubusercontent.com/74920990/104563675-3b74a180-564a-11eb-928b-49c83c84e4e1.png)

PS: Thanks a lot for this theme(s)!

**Comment by glatteispogo** [comment]
Maybe you could just use the color for marked text to solve this fast and easy?

![grafik](https://user-images.githubusercontent.com/74920990/104591025-6a037400-566c-11eb-82a7-b0cf9d9281c2.png)

**Comment by calrobertlee** [comment]
Hey! Thanks for bringing this to my attention, I've scrapped together a quick fix for you.  Please add this code below your import line.  Together, it should all look like:
```
@import url('https://calrobertlee.github.io/roam-themes/lux.css');

.rm-embed-container {
background-color: hsl(213, 10%, 16%);
    border-left: 4px solid rgba(255, 0, 0, .2);
}

.rm-embed-container .rm-embed-container {
background-color: hsl(213, 10%, 14%);
    border-left: 4px solid rgba(255, 145, 0, .2);
}

.rm-embed-container .rm-embed-container .rm-embed-container{
background-color: hsl(213, 10%, 12%);
    border-left: 4px solid rgba(255, 221, 0, .2);
}
```

or replace with nox.css if you are using that theme instead

I'll add this to the actual code later today!
