### ISSUE TITLE
Cannot click on menu (settings, favortites, etc.) 

### ISSUE THREAD

**Issue by joshkal** [calrobertlee/roam-css-styles#24]
When using:  
@import url('https://calrobertlee.github.io/roam-themes/nox.css'); 

I'm unable to click on any of the top right menu buttons (settings, favorites, graph, filter). The search still works. When I remove the code from roam/css the menu items instantly work again. 

Thanks for creating this great dark mode code!! I love it!

**Comment by robertomb** [comment]
Same here!

**Comment by drusellers** [comment]
Confirmed here as well

**Comment by joshkal** [comment]
Another issue that is maybe the same or a related issue: when I minimize the top left menu button, I can't open it back up. Clicking on the 3 bar menu doesn't work to open it back up. Works when I remove the code, like my previously posted issue.

**Comment by mpjacob** [comment]
Same here! Only the search button works. Seems to be because only the search button is above (depth) the note section whereas the rest are below and trying to click on them triggers note title change instead of the expected action.
________________________________

**Comment by glatteispogo** [comment]
confirm

**Comment by boydean41** [comment]
Also confirm this for Nox and Lux :(

**Comment by calrobertlee** [comment]
Been swamped with work! Sorry everyone! Will get to it ASAP later today thanks for being so patient

**Comment by calrobertlee** [comment]
@drusellers @robertomb @mpjacob @joshkal

Updated! The Roam team changed a ton of stuff and it took a bit longer than expected to patch everything.
