### ISSUE TITLE
SELECT colors need some love

### ISSUE THREAD

**Issue by eatondpe** [calrobertlee/roam-css-styles#4]
I really like what you have here. And they way you laid it out makes it easy to read and adjust. For example, I wanted to keep the help button in the bottom right corner. Your organization and comments made that easy to find and comment out. Really nice!

One I can't find, though, is what is driving the colors for SELECTs.

For example, I have this code in my Roam:  `{{or: [[to read]] | [[reading]] | [[read]]}}`.

But it renders like this:  
![image](https://user-images.githubusercontent.com/67427527/87444073-50517900-c5c4-11ea-81fc-95f5d19bfa50.png)

On the actual page, it's much less readable than that screenshot.

**Comment by calrobertlee** [comment]
Thanks eatondpe! Really happy to hear that you like this project.

Also, thanks for bringing this to my attention, I never even knew Roam had this function!

I'm pushing the update now

**Comment by eatondpe** [comment]
Beautiful! Thank you.

![image](https://user-images.githubusercontent.com/67427527/87519062-17121b00-c64f-11ea-8d6d-9a3e04fb4947.png)

**Comment by calrobertlee** [comment]
👍
