### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by andrewg1978** [calrobertlee/roam-css-styles#6]
Hi Cal,

Really love your Nox theme for Roam
One big issue I am experiencing is that when searching - the search box ends up all the way on the left.
Unless I have the screen fully expanded I can't unfortunately see the items that come up in the search (they are cut off)

This really slows down my workflow and as a result - today I have finally had to switch the css-style back the default setting.

Hopefully this is something that you can fix to improve the functionality of your styles.

Keep up the great work

Andrew

**Comment by calrobertlee** [comment]
Fixed! Thanks for bringing this to my attention Andrew.

Import the entire theme using this line:
`@import url('https://calrobertlee.github.io/roam-themes/nox.css');`

Also, thanks for the kind words and I'm glad you are enjoying the theme.

-Cal

**Comment by andrewg1978** [comment]
Unfortunately this doesn't seem to have been fixed Cal
Apologies

<img width="724" alt="Screen Shot 2020-07-22 at 12 46 49" src="https://user-images.githubusercontent.com/64576070/88129311-20851f80-cc1b-11ea-9e1f-24d6f4c0f155.png">

**Comment by calrobertlee** [comment]
Apologies for closing the issue preemptively

Which browser are you using?  I'm unable to recreate your issue on 3 browsers (Safari, Chrome, Firefox).

To troubleshoot, may I ask if `@import url('https://calrobertlee.github.io/roam-themes/nox.css');` is the only line of code on your `[[roam/css]]` page?

It should look something like this in a code block:
![](https://i.imgur.com/sTldFLo.png)

**Comment by andrewg1978** [comment]
This works now - but only after I remove all other CSS themes 
When I return them - the same problem recurs - not sure exactly why
will just have to keep them somewhere else for now

Thanks

**Comment by calrobertlee** [comment]
Great! Glad we found a workaround.

You can load up your other themes using this extension: [Stylus Extension](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne?hl=en)

So you can quickly switch between all of them.

Cheers
