### ISSUE TITLE
Font-family and font-size

### ISSUE THREAD

**Issue by ivanddm** [calrobertlee/roam-css-styles#9]
Hi and thanks for such nice themes,

I want to change the font-family and font-size and I was under the impression that since you defined variables `--main-font` and `--main-font-size`, I could just change the font through those variables, but exploring your css it looks like it is not setup in that way.

Is this going to be added perhaps in the future?

**Comment by calrobertlee** [comment]
Hi ivanddm, glad you like the themes!

Thanks for reaching out with this long overdue update — I plan to get it done soon.

I will notify you when I have made the update

cheers!
